package app.pixsub.backend.payment.domain;

import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.time.LocalDate;

import static org.assertj.core.api.Assertions.assertThat;

class PaymentTest {
    @Test
    void newPending_createsPendingPaymentWithTimestampsAndNoIdOrPaidDate() {
        Long subscriptionId = 5L;
        long amountInCents = 100_00L;
        LocalDate dueDate = LocalDate.of(2025, 1, 15);

        Payment payment = Payment.newPending(subscriptionId, amountInCents, dueDate);

        // id is generated by DB later
        assertThat(payment.getId()).isNull();
        assertThat(payment.getSubscriptionId()).isEqualTo(subscriptionId);
        assertThat(payment.getAmountInCents()).isEqualTo(amountInCents);
        assertThat(payment.getDueDate()).isEqualTo(dueDate);

        // pending state
        assertThat(payment.getStatus()).isEqualTo(PaymentStatus.PENDING);
        assertThat(payment.getPaidDate()).isNull();

        // pix-related fields are not yet set
        assertThat(payment.getPixQrCode()).isNull();
        assertThat(payment.getPixCopyPaste()).isNull();
        assertThat(payment.getPixProviderPaymentId()).isNull();

        // timestamps are initialized
        assertThat(payment.getCreatedAt()).isNotNull();
        assertThat(payment.getUpdatedAt()).isNotNull();
        assertThat(payment.getCreatedAt())
                .isBeforeOrEqualTo(payment.getUpdatedAt());
    }

    @Test
    void markPaid_returnsNewInstanceWithPaidStatusAndPaidDate_preservingOtherFields() {
        Long subscriptionId = 5L;
        long amountInCents = 100_00L;
        LocalDate dueDate = LocalDate.of(2025, 1, 15);

        Payment original = new Payment(
                10L,
                subscriptionId,
                amountInCents,
                dueDate,
                null,
                PaymentStatus.PENDING,
                null,
                "QR",
                "COPY-PASTE",
                "PROV-ID",
                Instant.now().minusSeconds(120),
                Instant.now().minusSeconds(60)
        );

        Instant paidAt = Instant.now();

        Payment paid = original.markPaid(paidAt);

        // original is unchanged (immutability)
        assertThat(original.getStatus()).isEqualTo(PaymentStatus.PENDING);
        assertThat(original.getPaidDate()).isNull();

        // new instance has same identity-related fields
        assertThat(paid).isNotSameAs(original);
        assertThat(paid.getId()).isEqualTo(original.getId());
        assertThat(paid.getSubscriptionId()).isEqualTo(original.getSubscriptionId());
        assertThat(paid.getAmountInCents()).isEqualTo(original.getAmountInCents());
        assertThat(paid.getDueDate()).isEqualTo(original.getDueDate());

        // state changed to PAID with given paidAt
        assertThat(paid.getStatus()).isEqualTo(PaymentStatus.PAID);
        assertThat(paid.getPaidDate()).isEqualTo(paidAt);

        // pix fields preserved
        assertThat(paid.getPixQrCode()).isEqualTo(original.getPixQrCode());
        assertThat(paid.getPixCopyPaste()).isEqualTo(original.getPixCopyPaste());
        assertThat(paid.getPixProviderPaymentId()).isEqualTo(original.getPixProviderPaymentId());

        // createdAt preserved, updatedAt refreshed
        assertThat(paid.getCreatedAt()).isEqualTo(original.getCreatedAt());
        assertThat(paid.getUpdatedAt()).isAfterOrEqualTo(original.getUpdatedAt());
    }
}
