spring.application.name=backend

# TEMPORARY: disable DataSource autoconfiguration until we wire Postgres
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
